# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ELiquid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flavoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('producer', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Nicotine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=64)),
                ('concentration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsersFavouriteELiquids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliquid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.ELiquid')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.User')),
            ],
        ),
        migrations.CreateModel(
            name='UsersFlavoringInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('flavoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.Flavoring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.User')),
            ],
        ),
        migrations.CreateModel(
            name='UsersNicotineInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('nicotine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.Nicotine')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.User')),
            ],
        ),
        migrations.AddField(
            model_name='eliquid',
            name='flavoring',
            field=models.ManyToManyField(through='eLiquidInventory.Composition', to='eLiquidInventory.Flavoring'),
        ),
        migrations.AddField(
            model_name='composition',
            name='eLiquid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.ELiquid'),
        ),
        migrations.AddField(
            model_name='composition',
            name='flavorings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLiquidInventory.Flavoring'),
        ),
    ]
